/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package battleship;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class MainTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Main classUnderTest = new Main();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
